name:                ghci-reload-error-monadic-bang
version:             0.1.0.0
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"

dependencies:
- base >= 4.7 && < 5
- monadic-bang

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -fplugin=MonadicBang

executables:
  ghci-reload-error-monadic-bang-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
